### ISSUE TITLE
Fitness goals

### ISSUE THREAD

**Issue by jatins** [jatins/Life#14]
I have a hate-hate relationship with Gym and I eat all junk that comes my way. But I also want to get in shape.

(╯°□°）╯︵ ┻━┻

I won't be able to spend time at gym with #11 , however, I can spare some time for in-house exercises, and also get some dumbbells at home. 

Goals here:
- [ ] 100 pushups in 3 sets by end of year (I can do 15 now)
- [ ] Visible muscle gain (Don't have a clear target here)

**Comment by deepankerk** [comment]
So its July now! How far are you from your target of 100 pushups a day?

**Comment by jatins** [comment]
@Deeepanker *blocks you*
